- hosts: local
  become: true
  vars_files:
    - /home/ansible/roles/users_managerment/vars/main.yaml
    - /home/ansible/inventories/group_vars/all_vars.yaml
  tasks:
    - name: Run tasks delete_user from Users_managerment
      include_tasks:
        file: /home/ansible/roles/users_managerment/tasks/delete_user.yaml
      tags: delete_users